name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.2.1
